create database customer_behavior;
use customer_behavior;
show tables;
desc customer;
select * from customer;
-- what is the revenue generated by msel and female customers
select gender,sum(purchase_amount) as revenue
from customer
group by gender;
-- which customers used a discount but spent more than the
-- average purcahase amount
select customer_id,purchase_amount 
from customer
where discount_applied="Yes" and
purchase_amount>=(select avg(purchase_amount) from customer);

-- which are the top 5 product with the highest average review ratings
select item_purchased,round(avg(review_rating),2) as average_product_rating
from customer
group by item_purchased
order by average_product_rating desc
limit 5;
-- compare the average purchase amounts between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2) from 
customer where shipping_type in ("Standard","Express")
group by shipping_type;

-- do subscribed customers spend more ? compare average spend and total
-- revenue between subs and non subs
select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by average_spend,total_revenue desc;

-- which 5 product have the highest percentage of purchases of
-- with discount applied ?
select item_purchased,
round(sum(case when discount_applied ="yes" then 1 else 0 end)/count(*)*100,2) as discount
from customer
group by item_purchased
order by discount desc
limit 5;
-- segment customers based on the previous purchased into new,returnning,loyal
-- and count rach swegment
with cte as(
select customer_id,previous_purchases,
case
when previous_purchases=1 then "new"
when previous_purchases between 2 and 10 then "returnning"
else "loyal"
end as customer_segment
from customer
)
select customer_segment, count(*) as count
from cte
group by customer_segment;
-- what are the top 3 purchsed products within each category
with cte as(
select category,
item_purchased,
count(customer_id) as count,
row_number() over(partition by category order by count(customer_id) desc) as rk
from customer
group by category,item_purchased
) 
select rk,category,item_purchased,count
from cte 
where rk<=3;
-- are customers who are repeat buyers(more than 5 prevoius purchased) also likely to subscribe
select subscription_status,
count(customer_id) as count
from customer
where previous_purchases>5
group by subscription_status;
-- what is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
